from __future__ import annotations
"""
EduQuest Pro — AI Agent Exam Data Importer
Parses exam questions generated by external AI Agents (ChatGPT, Claude, Gemini, DeepSeek...)
from JSON, Microsoft Word (.docx), Markdown, or plain text formats.
"""

import io
import re
import json
import unicodedata
from typing import List, Dict, Any, Tuple, Optional

# Difficulty normalizer
DIFFICULTY_MAP = {
    "dễ": "easy",
    "de": "easy",
    "easy": "easy",
    "cơ bản": "easy",
    "co ban": "easy",
    "nhận biết": "easy",
    "trung bình": "medium",
    "trung binh": "medium",
    "vừa": "medium",
    "vua": "medium",
    "medium": "medium",
    "thông hiểu": "medium",
    "khó": "hard",
    "kho": "hard",
    "hard": "hard",
    "vận dụng": "hard",
    "vận dụng cao": "olympiad",
    "nâng cao": "olympiad",
    "nang cao": "olympiad",
    "olympiad": "olympiad",
    "olympic": "olympiad",
    "timo": "olympiad",
    "asmo": "olympiad",
}

SUBJECT_MAP = {
    "toán": "math",
    "toan": "math",
    "toán học": "math",
    "math": "math",
    "mathematics": "math",
    "tiếng việt": "vietnamese",
    "tieng viet": "vietnamese",
    "vietnamese": "vietnamese",
    "văn": "vietnamese",
    "tiếng anh": "english",
    "tieng anh": "english",
    "english": "english",
    "khoa học": "science",
    "khoa hoc": "science",
    "science": "science",
    "tnxh": "science",
    "tin học": "informatics",
    "tin hoc": "informatics",
    "informatics": "informatics",
}


def normalize_difficulty(val: Any) -> str:
    if not val:
        return "medium"
    s = str(val).strip().lower()
    return DIFFICULTY_MAP.get(s, "medium")


def normalize_subject(val: Any, default: str = "math") -> str:
    norm_default = SUBJECT_MAP.get(str(default or "").strip().lower(), default or "math")
    if not val:
        return norm_default
    s = str(val).strip().lower()
    return SUBJECT_MAP.get(s, norm_default)


def normalize_grade(val: Any, default: int = 5) -> int:
    if val is None:
        return default
    try:
        s = str(val).strip().lower()
        if any(k in s for k in ["mầm non", "mam non", "kindergarten", "tiền tiểu học", "preschool", "khối 0", "lớp 0"]):
            return 0
        if isinstance(val, (int, float)):
            g = int(val)
            return g if 0 <= g <= 12 else default
        m = re.search(r'\b(\d{1,2})\b', s)
        if m:
            g = int(m.group(1))
            return g if 0 <= g <= 12 else default
    except Exception:
        pass
    return default


def _clean_option_content(text: str) -> str:
    """Removes redundant leading option prefixes like 'A. ', 'B) ', '(C) '."""
    if not text:
        return ""
    s = str(text).strip()
    s = re.sub(r'^\(?[A-Da-d]\)?[\.\:\)\-]\s*', '', s).strip()
    return s


def normalize_options_list(raw_options: Any, correct_answer: str = "") -> List[Dict[str, Any]]:
    """Standardizes options into list of dicts: [{'id': 'A', 'content': '...', 'is_correct': bool}, ...]."""
    norm: List[Dict[str, Any]] = []
    letters = ["A", "B", "C", "D", "E", "F"]
    corr_upper = str(correct_answer or "").strip().upper()

    if isinstance(raw_options, dict):
        for k, v in raw_options.items():
            k_id = str(k).strip().upper()
            content = _clean_option_content(str(v))
            is_corr = (k_id == corr_upper)
            norm.append({
                "id": k_id,
                "content": content,
                "is_correct": is_corr
            })
    elif isinstance(raw_options, list):
        for idx, item in enumerate(raw_options):
            default_id = letters[idx] if idx < len(letters) else chr(65 + idx)
            if isinstance(item, dict):
                opt_id = str(item.get("id") or item.get("key") or item.get("label") or default_id).strip().upper()
                raw_c = item.get("content") or item.get("text") or item.get("value") or ""
                content = _clean_option_content(str(raw_c))
                is_corr = bool(item.get("is_correct")) or (opt_id == corr_upper)
                norm.append({
                    "id": opt_id,
                    "content": content,
                    "is_correct": is_corr
                })
            elif isinstance(item, str):
                s = item.strip()
                prefix_m = re.match(r'^\(?([A-Da-d])\)?[\.\:\)\-]\s*(.*)$', s)
                if prefix_m:
                    opt_id = prefix_m.group(1).upper()
                    content = _clean_option_content(prefix_m.group(2))
                else:
                    opt_id = default_id
                    content = _clean_option_content(s)
                is_corr = (opt_id == corr_upper)
                norm.append({
                    "id": opt_id,
                    "content": content,
                    "is_correct": is_corr
                })
            else:
                norm.append({
                    "id": default_id,
                    "content": str(item).strip(),
                    "is_correct": (default_id == corr_upper)
                })

    # Sort A, B, C, D
    norm.sort(key=lambda x: x["id"])
    return norm


def parse_json_questions(
    data: Any,
    default_grade: int = 5,
    default_subject: str = "math",
    default_topic: str = "AI Agent"
) -> List[Dict[str, Any]]:
    """Extracts questions from parsed JSON structure (list or dict)."""
    default_subject = normalize_subject(default_subject, "math")
    raw_list: List[Dict[str, Any]] = []

    if isinstance(data, list):
        raw_list = [x for x in data if isinstance(x, dict)]
    elif isinstance(data, dict):
        for key in ["questions", "items", "data", "exam", "question_list", "cau_hoi", "danh_sach_cau_hoi"]:
            if key in data and isinstance(data[key], list):
                raw_list = [x for x in data[key] if isinstance(x, dict)]
                break
        if not raw_list:
            raw_list = [data]

    result: List[Dict[str, Any]] = []

    for idx, item in enumerate(raw_list):
        q_num = item.get("question_number") or item.get("q_number") or (idx + 1)
        stem = str(
            item.get("question_text") or
            item.get("question") or
            item.get("content_text") or
            item.get("content") or
            item.get("stem") or
            item.get("cau_hoi") or
            item.get("de_bai") or ""
        ).strip()

        if not stem or len(stem) < 3:
            continue

        raw_opts = item.get("options") or item.get("choices") or item.get("phuong_an") or item.get("dap_an_lua_chon") or []
        corr = str(
            item.get("correct_answer") or
            item.get("answer") or
            item.get("dap_an") or
            item.get("correct") or
            item.get("key") or ""
        ).strip().upper()
        # Clean answer if it's like "Đáp án A" or "A. 40"
        m_corr = re.search(r'\b([A-D])\b', corr)
        if m_corr:
            corr = m_corr.group(1)

        norm_opts = normalize_options_list(raw_opts, corr)

        # If options are embedded in stem
        if not norm_opts and "\n" in stem:
            lines = stem.split("\n")
            cand_opts = []
            cand_stem = []
            for ln in lines:
                s_ln = ln.strip()
                if re.match(r'^\(?[A-D]\)?[\.\:\)\-]\s*', s_ln):
                    cand_opts.append(s_ln)
                else:
                    cand_stem.append(ln)
            if cand_opts:
                norm_opts = normalize_options_list(cand_opts, corr)
                stem = "\n".join(cand_stem).strip()

        # If corr wasn't found, check if an option is flagged is_correct
        if not corr and norm_opts:
            for opt in norm_opts:
                if opt.get("is_correct"):
                    corr = opt["id"]
                    break
        if not corr and norm_opts:
            corr = "A"

        # Update options is_correct
        for opt in norm_opts:
            opt["is_correct"] = (opt["id"] == corr)

        expl = str(
            item.get("explanation") or
            item.get("solution") or
            item.get("loi_giai") or
            item.get("huong_dan_giai") or
            item.get("giai_thich") or ""
        ).strip()

        grade = normalize_grade(item.get("grade") or item.get("khoi_lop") or item.get("lop"), default_grade)
        diff = normalize_difficulty(item.get("difficulty") or item.get("do_kho") or item.get("muc_do"))
        subj = normalize_subject(item.get("subject") or item.get("mon_hoc"), default_subject)
        topic = str(item.get("topic") or item.get("chuyen_de") or item.get("chu_de") or default_topic).strip()

        q_obj = {
            "question_number": q_num,
            "content_text": stem,
            "content_html": f"<p>{stem}</p>",
            "options": norm_opts,
            "correct_answer": corr,
            "explanation": expl,
            "grade": grade,
            "difficulty": diff,
            "subject": subj,
            "topic": topic,
            "source_platform": "ai_agent_import",
            "question_type": "single_choice" if len(norm_opts) >= 2 else "fill_blank",
            "has_handwriting": bool(item.get("has_handwriting", False)),
            "images": item.get("images") or []
        }
        result.append(q_obj)

    return result


def parse_text_or_markdown_questions(
    text: str,
    default_grade: int = 5,
    default_subject: str = "math",
    default_topic: str = "AI Agent"
) -> List[Dict[str, Any]]:
    """
    Parses plain text or Markdown containing multiple questions separated by
    patterns like 'Câu 1:', '### Câu 1', 'Bài 1:', or '1.'.
    """
    if not text or not text.strip():
        return []

    default_subject = normalize_subject(default_subject, "math")
    clean_text = text.strip()

    # Split into chunks based on question starters
    pattern_split = re.compile(
        r'(?:^|\n)(?=(?:#{1,4}\s*)?(?:Câu\s*(?:hỏi)?\s*\d+|Question\s*\d+|Bài\s*(?:tập)?\s*\d+)[\s\.\:\-_])',
        re.IGNORECASE
    )
    chunks = pattern_split.split(clean_text)

    # Fallback split: e.g. "1. ", "2. ", "3. " if no "Câu" header found
    if len(chunks) <= 1:
        pattern_num_split = re.compile(r'(?:^|\n)(?=\d+[\.\)]\s+[^\n]{5,})')
        cand_chunks = pattern_num_split.split(clean_text)
        if len(cand_chunks) > 1:
            chunks = cand_chunks

    result: List[Dict[str, Any]] = []

    for idx, raw_chunk in enumerate(chunks):
        chunk = raw_chunk.strip()
        if not chunk or len(chunk) < 10:
            continue

        # Extract Question Number
        q_num = idx + 1
        num_m = re.match(r'^(?:#{1,4}\s*)?(?:câu\s*(?:hỏi)?\s*|question\s*|bài\s*(?:tập)?\s*)?(\d+)[\s\.\:\-_]*', chunk, re.IGNORECASE)
        if num_m:
            try:
                q_num = int(num_m.group(1))
            except Exception:
                pass

        # Extract Correct Answer
        corr = "A"
        ans_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:đáp\s*án|đ/a|answer|key|chọn|đáp\s*số)(?:\*\*)?\s*[\:\-\=]?\s*(?:\*\*)?([A-D])\b',
            chunk,
            re.IGNORECASE
        )
        if ans_m:
            corr = ans_m.group(1).upper()

        # Extract Grade
        grade = default_grade
        grade_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:khối\s*lớp|khối|lớp|grade)(?:\*\*)?\s*[\:\-\=]?\s*(\d{1,2})\b',
            chunk,
            re.IGNORECASE
        )
        if grade_m:
            grade = normalize_grade(grade_m.group(1), default_grade)

        # Extract Difficulty
        diff = "medium"
        diff_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:mức\s*độ|độ\s*khó|difficulty)(?:\*\*)?\s*[\:\-\=]?\s*([^\n\*\#]+)',
            chunk,
            re.IGNORECASE
        )
        if diff_m:
            diff = normalize_difficulty(diff_m.group(1))

        # Extract Topic
        topic = default_topic
        topic_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:chuyên\s*đề|chủ\s*đề|topic|dạng\s*bài)(?:\*\*)?\s*[\:\-\=]?\s*([^\n\*\#]+)',
            chunk,
            re.IGNORECASE
        )
        if topic_m:
            topic = topic_m.group(1).strip()

        # Extract Subject
        subj = default_subject
        subj_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:môn\s*học|môn|subject)(?:\*\*)?\s*[\:\-\=]?\s*([^\n\*\#]+)',
            chunk,
            re.IGNORECASE
        )
        if subj_m:
            subj = normalize_subject(subj_m.group(1), default_subject)

        # Extract Explanation
        expl = ""
        expl_m = re.search(
            r'(?:^|\n)\s*(?:\*\*)?(?:lời\s*giải|hướng\s*dẫn\s*giải|giải\s*thích|explanation|solution|hdg)(?:\*\*)?\s*[\:\-\=]?\s*([\s\S]*?)(?=(?:\n\s*(?:\*\*)?(?:khối|lớp|mức|độ\s*khó|chuyên\s*đề|chủ\s*đề|môn))|$)',
            chunk,
            re.IGNORECASE
        )
        if expl_m:
            expl = expl_m.group(1).strip()

        # Extract Options A, B, C, D
        raw_options: List[Dict[str, Any]] = []
        opt_matches = re.findall(
            r'(?:^|\n)\s*(?:[-*•]\s*)?\(?([A-D])\)?[\.\:\)\-]\s*([^\n]+)',
            chunk,
            re.IGNORECASE
        )
        if opt_matches:
            seen_ids = set()
            for opt_id, opt_text in opt_matches:
                clean_id = opt_id.upper()
                if clean_id not in seen_ids:
                    seen_ids.add(clean_id)
                    # Don't capture metadata inside option text
                    clean_c = re.split(r'\s*(?:Đ/A|Đáp án|Lời giải|Khối|Mức độ)\s*[\:\-]', opt_text, flags=re.IGNORECASE)[0].strip()
                    clean_c = _clean_option_content(clean_c)
                    raw_options.append({
                        "id": clean_id,
                        "content": clean_c,
                        "is_correct": (clean_id == corr)
                    })

        # Extract Stem (Question text)
        # Strip header e.g. "Câu 1: " or "### Câu 1."
        stem_text = re.sub(
            r'^(?:#{1,4}\s*)?(?:câu\s*(?:hỏi)?\s*\d+|question\s*\d+|bài\s*(?:tập)?\s*\d+|\d+[\.\)])[\s\.\:\-_]*',
            '',
            chunk,
            flags=re.IGNORECASE
        ).strip()

        # Truncate metadata from stem_text
        stem_lines = []
        for line in stem_text.split("\n"):
            s_line = line.strip()
            # Stop if reached options, answers, explanations, or metadata tags
            if re.match(r'^(?:[-*•]\s*)?\(?[A-D]\)?[\.\:\)\-]', s_line):
                break
            if re.match(r'^(?:\*\*)?(?:đáp\s*án|lời\s*giải|hướng\s*dẫn|khối|mức\s*độ|chuyên\s*đề)', s_line, re.IGNORECASE):
                break
            stem_lines.append(line)

        final_stem = "\n".join(stem_lines).strip()
        if not final_stem:
            final_stem = stem_text.split("\n")[0].strip()

        if len(final_stem) < 3:
            continue

        q_obj = {
            "question_number": q_num,
            "content_text": final_stem,
            "content_html": f"<p>{final_stem}</p>",
            "options": raw_options,
            "correct_answer": corr,
            "explanation": expl,
            "grade": grade,
            "difficulty": diff,
            "subject": subj,
            "topic": topic,
            "source_platform": "ai_agent_import",
            "question_type": "single_choice" if len(raw_options) >= 2 else "fill_blank",
            "has_handwriting": False,
            "images": []
        }
        result.append(q_obj)

    return result


def parse_docx_bytes(file_bytes: bytes) -> str:
    """Extracts all text from a .docx file using python-docx."""
    try:
        import docx
        doc = docx.Document(io.BytesIO(file_bytes))
        full_text = []
        for p in doc.paragraphs:
            if p.text and p.text.strip():
                full_text.append(p.text.strip())
        for table in doc.tables:
            for row in table.rows:
                row_cells = [cell.text.strip() for cell in row.cells if cell.text.strip()]
                if row_cells:
                    full_text.append(" | ".join(row_cells))
        return "\n".join(full_text)
    except Exception as e:
        print(f"[parse_docx_bytes] Lỗi khi đọc DOCX: {e}")
        return ""


def parse_ai_agent_payload(
    content: str | bytes,
    filename: str = "",
    default_grade: int = 5,
    default_subject: str = "math",
    default_topic: str = "Đề thi AI Agent"
) -> Tuple[List[Dict[str, Any]], List[str]]:
    """
    Main entry point for AI Agent exam data parsing.
    Accepts string or bytes payload, handles JSON, DOCX, Markdown, and plain text formats.
    Returns: (list_of_questions, list_of_warnings)
    """
    warnings: List[str] = []
    default_subject = normalize_subject(default_subject, "math")
    text_to_parse = ""

    # 1. Check if DOCX
    if isinstance(content, bytes) and (filename.lower().endswith(".docx") or content.startswith(b"PK\x03\x04")):
        text_to_parse = parse_docx_bytes(content)
        if not text_to_parse:
            warnings.append("Không thể trích xuất văn bản từ tệp Word (.docx). Vui lòng kiểm tra lại định dạng tệp.")
            return [], warnings
    elif isinstance(content, bytes):
        try:
            text_to_parse = content.decode("utf-8")
        except UnicodeDecodeError:
            try:
                text_to_parse = content.decode("latin-1")
            except Exception as e:
                warnings.append(f"Lỗi giải mã ký tự UTF-8: {e}")
                return [], warnings
    else:
        text_to_parse = str(content)

    clean_str = text_to_parse.strip()
    if not clean_str:
        warnings.append("Nội dung nhập rỗng, vui lòng dán dữ liệu hoặc tải tệp lên.")
        return [], warnings

    # 2. Check if JSON
    parsed_questions: List[Dict[str, Any]] = []

    # Attempt to locate JSON array or object
    cand_json = None
    fence_m = re.findall(r'```(?:json)?\s*([\s\S]*?)\s*```', clean_str, re.IGNORECASE)
    for fm in fence_m:
        try:
            cand = json.loads(fm, strict=False)
            if cand:
                cand_json = cand
                break
        except Exception:
            pass

    if cand_json is None and (clean_str.startswith("[") or clean_str.startswith("{") or "[\n" in clean_str):
        try:
            cand_json = json.loads(clean_str, strict=False)
        except Exception:
            # Try finding bracket slice
            arr_m = re.search(r'\[\s*\{[\s\S]*\}\s*\]', clean_str)
            if arr_m:
                try:
                    cand_json = json.loads(arr_m.group(0), strict=False)
                except Exception:
                    pass

    if cand_json is not None:
        try:
            parsed_questions = parse_json_questions(
                cand_json,
                default_grade=default_grade,
                default_subject=default_subject,
                default_topic=default_topic
            )
        except Exception as e:
            warnings.append(f"Lỗi cấu trúc khi đọc JSON: {e}. Hệ thống sẽ chuyển sang phân tích dạng văn bản tự do.")

    # 3. Fallback to Text / Markdown Parser if JSON returned nothing
    if not parsed_questions:
        parsed_questions = parse_text_or_markdown_questions(
            clean_str,
            default_grade=default_grade,
            default_subject=default_subject,
            default_topic=default_topic
        )

    # 4. Final Validation & Quality Checks
    valid_qs: List[Dict[str, Any]] = []
    for idx, q in enumerate(parsed_questions):
        # Validate stem
        if not q.get("content_text") or len(q["content_text"].strip()) < 4:
            warnings.append(f"Câu {idx + 1} bị bỏ qua do nội dung câu hỏi quá ngắn hoặc rỗng.")
            continue

        # Check options
        opts = q.get("options") or []
        if len(opts) < 2:
            warnings.append(f"Câu {idx + 1} ('{q['content_text'][:40]}...'): Chỉ tìm thấy {len(opts)} phương án trắc nghiệm.")

        # Ensure correct answer exists
        corr = q.get("correct_answer") or "A"
        q["correct_answer"] = corr
        q["has_handwriting"] = bool(q.get("has_handwriting", False))

        valid_qs.append(q)

    if not valid_qs:
        warnings.append("Không thể trích xuất câu hỏi nào hợp lệ từ dữ liệu đã cung cấp. Vui lòng kiểm tra định dạng theo mẫu.")

    return valid_qs, warnings


def get_ai_agent_template_info() -> Dict[str, Any]:
    """Returns standardized system prompt and schemas for external AI agents."""
    system_prompt = (
        "Bạn là Chuyên gia Khảo thí và Thiết kế Đề thi Giáo dục Hàng đầu Việt Nam.\n"
        "Nhiệm vụ của bạn là phân tích đề thi/ảnh bài tập và trích xuất TOÀN BỘ các câu hỏi trắc nghiệm thành dữ liệu có cấu trúc để nhập vào Ngân hàng Câu hỏi EduQuest Pro.\n\n"
        "YÊU CẦU BẮT BUỘC:\n"
        "1. Giải bài toán logic, chính xác để xác định đáp án đúng (A, B, C, hoặc D).\n"
        "2. Viết hướng dẫn giải (explanation) chi tiết từng bước, dễ hiểu cho học sinh và giáo viên.\n"
        "3. Tách bạch phần câu hỏi (question) và 4 phương án (options A, B, C, D), không để phương án lẫn trong câu hỏi.\n"
        "4. Xác định khối lớp (grade: 1-12) và mức độ khó (difficulty: easy | medium | hard | olympiad).\n"
        "5. Phát hiện chữ viết tay (has_handwriting: true nếu đề thi có vết chữ viết tay, chữ nháp của học sinh hoặc lời giải viết tay của giáo viên; false nếu là văn bản in/đánh máy hoàn toàn).\n\n"
        "HÃY XUẤT ĐẦU RA THEO ĐÚNG MỘT MẢNG JSON NHƯ SAU (Bắt đầu bằng [ và kết thúc bằng ]):\n"
        "[\n"
        "  {\n"
        "    \"question_number\": 1,\n"
        "    \"question\": \"Nội dung câu hỏi đầy đủ, bao gồm dữ kiện và câu hỏi...\",\n"
        "    \"options\": [\n"
        "      {\"id\": \"A\", \"content\": \"Nội dung phương án A\"},\n"
        "      {\"id\": \"B\", \"content\": \"Nội dung phương án B\"},\n"
        "      {\"id\": \"C\", \"content\": \"Nội dung phương án C\"},\n"
        "      {\"id\": \"D\", \"content\": \"Nội dung phương án D\"}\n"
        "    ],\n"
        "    \"correct_answer\": \"A\",\n"
        "    \"explanation\": \"Lời giải chi tiết từng bước, lý giải tại sao chọn A...\",\n"
        "    \"grade\": 4,\n"
        "    \"difficulty\": \"medium\",\n"
        "    \"subject\": \"Toán\",\n"
        "    \"topic\": \"Hình học\",\n"
        "    \"has_handwriting\": false\n"
        "  }\n"
        "]"
    )

    sample_json = [
        {
            "question_number": 1,
            "question": "Một hình chữ nhật có chiều dài 12 cm và chiều rộng 7 cm. Diện tích của hình chữ nhật đó là bao nhiêu?",
            "options": [
                {"id": "A", "content": "84 cm²"},
                {"id": "B", "content": "38 cm²"},
                {"id": "C", "content": "94 cm²"},
                {"id": "D", "content": "72 cm²"}
            ],
            "correct_answer": "A",
            "explanation": "Diện tích hình chữ nhật được tính theo công thức S = dài x rộng. Do đó: S = 12 x 7 = 84 (cm²).",
            "grade": 4,
            "difficulty": "easy",
            "subject": "Toán",
            "topic": "Hình học & Diện tích",
            "has_handwriting": False
        },
        {
            "question_number": 2,
            "question": "Tìm số tự nhiên x biết: 45 + x : 5 = 60.",
            "options": [
                {"id": "A", "content": "x = 75"},
                {"id": "B", "content": "x = 15"},
                {"id": "C", "content": "x = 3"},
                {"id": "D", "content": "x = 100"}
            ],
            "correct_answer": "A",
            "explanation": "Ta có: x : 5 = 60 - 45 => x : 5 = 15 => x = 15 x 5 => x = 75.",
            "grade": 4,
            "difficulty": "medium",
            "subject": "Toán",
            "topic": "Tìm thành phần chưa biết",
            "has_handwriting": False
        }
    ]

    sample_text = (
        "Câu 1: Một hình chữ nhật có chiều dài 12 cm và chiều rộng 7 cm. Diện tích của hình chữ nhật đó là bao nhiêu?\n"
        "A. 84 cm²\n"
        "B. 38 cm²\n"
        "C. 94 cm²\n"
        "D. 72 cm²\n"
        "Đáp án: A\n"
        "Khối lớp: 4\n"
        "Mức độ: Dễ\n"
        "Chuyên đề: Hình học & Diện tích\n"
        "Lời giải: Diện tích hình chữ nhật là S = 12 x 7 = 84 (cm²).\n\n"
        "Câu 2: Tìm số tự nhiên x biết: 45 + x : 5 = 60.\n"
        "A. x = 75\n"
        "B. x = 15\n"
        "C. x = 3\n"
        "D. x = 100\n"
        "Đáp án: A\n"
        "Khối lớp: 4\n"
        "Mức độ: Vừa\n"
        "Chuyên đề: Tìm thành phần chưa biết\n"
        "Lời giải: Ta có x : 5 = 60 - 45 = 15 => x = 15 x 5 = 75."
    )

    return {
        "system_prompt": system_prompt,
        "sample_json": sample_json,
        "sample_json_str": json.dumps(sample_json, ensure_ascii=False, indent=2),
        "sample_text": sample_text,
        "fields": [
            {"name": "question", "required": True, "description": "Nội dung câu hỏi (đề bài)"},
            {"name": "options", "required": True, "description": "4 phương án lựa chọn A, B, C, D"},
            {"name": "correct_answer", "required": True, "description": "Ký tự đáp án đúng ('A', 'B', 'C', hoặc 'D')"},
            {"name": "explanation", "required": True, "description": "Hướng dẫn lời giải chi tiết từng bước"},
            {"name": "grade", "required": True, "description": "Khối lớp (số nguyên từ 1 đến 12)"},
            {"name": "difficulty", "required": True, "description": "Mức độ khó ('easy', 'medium', 'hard', 'olympiad')"},
            {"name": "subject", "required": False, "description": "Môn học (Toán, Tiếng Việt, Tiếng Anh...)"},
            {"name": "topic", "required": False, "description": "Chuyên đề hoặc dạng bài toán"}
        ]
    }
