// EduQuest Pro — AI Agent Exam Importer & Parser Module
// Supports importing questions generated by external AI agents (ChatGPT, Claude, Gemini, DeepSeek...)
// from JSON, Word (.docx), Markdown, and plain text formats.

let currentAiParsedQuestions = [];
let selectedAiFile = null;
let aiTemplateData = null;

// ============================================================================
// 1. Modal Lifecycle & Tab Navigation
// ============================================================================

async function openAiAgentImportModal() {
  const modal = document.getElementById("modal-ai-agent-import");
  if (!modal) return;
  modal.style.display = "flex";

  // Load template info if not already loaded
  if (!aiTemplateData) {
    try {
      const res = await fetch(`${API_BASE}/import/ai-agent-template`);
      if (res.ok) {
        const data = await res.json();
        aiTemplateData = data.template || {};
        const promptEl = document.getElementById("ai-system-prompt-text");
        if (promptEl && aiTemplateData.system_prompt) {
          promptEl.value = aiTemplateData.system_prompt;
        }
      }
    } catch (e) {
      console.warn("Could not load AI template data:", e);
    }
  }

  // Default to paste tab
  switchAiImportTab("paste");
  setupAiDropzoneEvents();
}
window.openAiAgentImportModal = openAiAgentImportModal;

function closeAiAgentImportModal() {
  const modal = document.getElementById("modal-ai-agent-import");
  if (modal) modal.style.display = "none";
}
window.closeAiAgentImportModal = closeAiAgentImportModal;

function switchAiImportTab(tabName) {
  const tabs = ["paste", "file", "prompt"];
  tabs.forEach(t => {
    const btn = document.getElementById(`tab-btn-ai-${t}`);
    const content = document.getElementById(`ai-tab-content-${t}`);
    if (btn) {
      if (t === tabName) {
        btn.classList.add("active");
        btn.style.color = "#4f46e5";
        btn.style.borderBottomColor = "#4f46e5";
        btn.style.fontWeight = "700";
      } else {
        btn.classList.remove("active");
        btn.style.color = "#64748b";
        btn.style.borderBottomColor = "transparent";
        btn.style.fontWeight = "600";
      }
    }
    if (content) {
      content.style.display = (t === tabName) ? "flex" : "none";
    }
  });
}
window.switchAiImportTab = switchAiImportTab;

// ============================================================================
// 2. Sample Data & Template Helpers
// ============================================================================

function loadSampleAiJson() {
  const textarea = document.getElementById("ai-import-raw-text");
  if (!textarea) return;
  if (aiTemplateData && aiTemplateData.sample_json_str) {
    textarea.value = aiTemplateData.sample_json_str;
  } else {
    textarea.value = JSON.stringify([
      {
        "question_number": 1,
        "question": "Một hình chữ nhật có chiều dài 12 cm và chiều rộng 7 cm. Diện tích của hình chữ nhật đó là bao nhiêu?",
        "options": [
          { "id": "A", "content": "84 cm²" },
          { "id": "B", "content": "38 cm²" },
          { "id": "C", "content": "94 cm²" },
          { "id": "D", "content": "72 cm²" }
        ],
        "correct_answer": "A",
        "explanation": "Diện tích hình chữ nhật là S = 12 x 7 = 84 (cm²).",
        "grade": 4,
        "difficulty": "easy",
        "subject": "Toán",
        "topic": "Hình học & Diện tích"
      }
    ], null, 2);
  }
  showToast("Đã nạp mẫu JSON chuẩn!", "info");
}
window.loadSampleAiJson = loadSampleAiJson;

function loadSampleAiText() {
  const textarea = document.getElementById("ai-import-raw-text");
  if (!textarea) return;
  if (aiTemplateData && aiTemplateData.sample_text) {
    textarea.value = aiTemplateData.sample_text;
  } else {
    textarea.value = "Câu 1: Một hình chữ nhật có chiều dài 12 cm và chiều rộng 7 cm. Diện tích là bao nhiêu?\nA. 84 cm²\nB. 38 cm²\nC. 94 cm²\nD. 72 cm²\nĐáp án: A\nKhối lớp: 4\nMức độ: Dễ\nLời giải: Diện tích hình chữ nhật là 12 x 7 = 84 (cm²).";
  }
  showToast("Đã nạp mẫu Văn bản đề thi chuẩn!", "info");
}
window.loadSampleAiText = loadSampleAiText;

function clearAiImportText() {
  const textarea = document.getElementById("ai-import-raw-text");
  if (textarea) textarea.value = "";
}
window.clearAiImportText = clearAiImportText;

async function copyAiSystemPrompt() {
  const promptEl = document.getElementById("ai-system-prompt-text");
  if (!promptEl || !promptEl.value) return;
  try {
    await navigator.clipboard.writeText(promptEl.value);
    showToast("✓ Đã sao chép System Prompt! Hãy dán vào ChatGPT / Claude / Gemini.", "success");
  } catch (err) {
    promptEl.select();
    document.execCommand("copy");
    showToast("✓ Đã sao chép System Prompt!", "success");
  }
}
window.copyAiSystemPrompt = copyAiSystemPrompt;

function downloadSampleAiJson() {
  const text = (aiTemplateData && aiTemplateData.sample_json_str) || "[]";
  const blob = new Blob([text], { type: "application/json;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "mau_cau_hoi_ai_agent.json";
  a.click();
  URL.revokeObjectURL(url);
  showToast("Đã tải xuống file mau_cau_hoi_ai_agent.json", "success");
}
window.downloadSampleAiJson = downloadSampleAiJson;

// ============================================================================
// 3. File Dropzone & Selection
// ============================================================================

function handleAiFileSelect(event) {
  const files = event.target.files;
  if (!files || files.length === 0) return;
  selectedAiFile = files[0];

  const badge = document.getElementById("ai-selected-file-badge");
  const nameEl = document.getElementById("ai-selected-file-name");
  const sizeEl = document.getElementById("ai-selected-file-size");

  if (badge && nameEl && sizeEl) {
    badge.style.display = "flex";
    nameEl.textContent = selectedAiFile.name;
    sizeEl.textContent = `(${(selectedAiFile.size / 1024).toFixed(1)} KB)`;
  }
}
window.handleAiFileSelect = handleAiFileSelect;

function clearSelectedAiFile() {
  selectedAiFile = null;
  const input = document.getElementById("ai-file-input");
  if (input) input.value = "";
  const badge = document.getElementById("ai-selected-file-badge");
  if (badge) badge.style.display = "none";
}
window.clearSelectedAiFile = clearSelectedAiFile;

function setupAiDropzoneEvents() {
  const dropzone = document.getElementById("ai-file-dropzone");
  if (!dropzone || dropzone._dragInit) return;
  dropzone._dragInit = true;

  dropzone.addEventListener("dragover", (e) => {
    e.preventDefault();
    e.stopPropagation();
    dropzone.style.borderColor = "#4f46e5";
    dropzone.style.background = "#eef2ff";
  });

  ["dragleave", "dragend"].forEach(type => {
    dropzone.addEventListener(type, (e) => {
      e.preventDefault();
      e.stopPropagation();
      dropzone.style.borderColor = "#cbd5e1";
      dropzone.style.background = "#f8fafc";
    });
  });

  dropzone.addEventListener("drop", (e) => {
    e.preventDefault();
    e.stopPropagation();
    dropzone.style.borderColor = "#cbd5e1";
    dropzone.style.background = "#f8fafc";
    if (e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      handleAiFileSelect({ target: { files: e.dataTransfer.files } });
    }
  });
}
window.setupAiDropzoneEvents = setupAiDropzoneEvents;
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", setupAiDropzoneEvents);
} else {
  setupAiDropzoneEvents();
}

// ============================================================================
// 4. Execution Logic (Text & File)
// ============================================================================

async function executeAiImport(saveToBank = false) {
  const rawText = document.getElementById("ai-import-raw-text")?.value?.trim() || "";
  if (!rawText) {
    showToast("Vui lòng dán dữ liệu JSON hoặc văn bản đề thi", "warning");
    return;
  }

  const defaultGrade = parseInt(document.getElementById("ai-import-default-grade")?.value) || 5;
  const defaultSubject = document.getElementById("ai-import-default-subject")?.value || "math";
  const defaultTopic = document.getElementById("ai-import-default-topic")?.value?.trim() || "Đề thi AI Agent";

  const btnPreview = document.getElementById("btn-ai-preview");
  const btnSave = document.getElementById("btn-ai-save-direct");

  if (btnPreview) btnPreview.disabled = true;
  if (btnSave) btnSave.disabled = true;

  try {
    const res = await fetch(`${API_BASE}/import/ai-agent-data`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        raw_text: rawText,
        save_to_bank: saveToBank,
        default_grade: defaultGrade,
        default_subject: defaultSubject,
        default_topic: defaultTopic
      })
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.detail || `Lỗi HTTP ${res.status}`);
    }

    const data = await res.json();
    const questions = data.questions || [];
    currentAiParsedQuestions = questions;

    renderAiImportPreview(questions, data.warnings || []);

    if (saveToBank) {
      showToast(`🎉 Đã lưu thành công ${data.saved_count || questions.length} câu hỏi vào Ngân hàng CSDL!`, "success");
      loadDashboardStats();
      if (typeof State !== "undefined" && State.currentView === "bank") loadQuestions();
      if (typeof broadcastNewQuestions === "function") {
        broadcastNewQuestions(data.saved_count || questions.length, "AI Agent Import");
      }
    } else {
      showToast(`✓ Đã nhận diện thành công ${questions.length} câu hỏi! Xem trước bên dưới.`, "success");
    }

  } catch (err) {
    showToast(`Lỗi khi xử lý dữ liệu: ${err.message}`, "error");
  } finally {
    if (btnPreview) btnPreview.disabled = false;
    if (btnSave) btnSave.disabled = false;
  }
}
window.executeAiImport = executeAiImport;

async function executeAiFileImport(saveToBank = false) {
  if (!selectedAiFile) {
    showToast("Vui lòng chọn hoặc kéo thả tệp (.json, .docx, .txt) trước!", "warning");
    return;
  }

  const defaultGrade = parseInt(document.getElementById("ai-import-default-grade")?.value) || 5;
  const defaultSubject = document.getElementById("ai-import-default-subject")?.value || "math";
  const defaultTopic = document.getElementById("ai-import-default-topic")?.value?.trim() || "Đề thi AI Agent";

  const formData = new FormData();
  formData.append("file", selectedAiFile);
  formData.append("save_to_bank", saveToBank ? "true" : "false");
  formData.append("default_grade", String(defaultGrade));
  formData.append("default_subject", defaultSubject);
  formData.append("default_topic", defaultTopic);

  try {
    const res = await fetch(`${API_BASE}/import/ai-agent-data`, {
      method: "POST",
      body: formData
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.detail || `Lỗi HTTP ${res.status}`);
    }

    const data = await res.json();
    const questions = data.questions || [];
    currentAiParsedQuestions = questions;

    renderAiImportPreview(questions, data.warnings || []);

    if (saveToBank) {
      showToast(`🎉 Đã lưu thành công ${data.saved_count || questions.length} câu hỏi từ tệp "${selectedAiFile.name}"!`, "success");
      loadDashboardStats();
      if (typeof State !== "undefined" && State.currentView === "bank") loadQuestions();
      if (typeof broadcastNewQuestions === "function") {
        broadcastNewQuestions(data.saved_count || questions.length, "Tệp AI Agent");
      }
    } else {
      showToast(`✓ Đã nhận diện thành công ${questions.length} câu hỏi từ tệp "${selectedAiFile.name}"!`, "success");
    }

  } catch (err) {
    showToast(`Lỗi khi đọc tệp: ${err.message}`, "error");
  }
}
window.executeAiFileImport = executeAiFileImport;

// ============================================================================
// 5. Render Preview & Actions
// ============================================================================

function renderAiImportPreview(questions, warnings = []) {
  const container = document.getElementById("ai-preview-container");
  const countBadge = document.getElementById("ai-preview-count-badge");
  const warnBadge = document.getElementById("ai-preview-warn-badge");
  const listEl = document.getElementById("ai-preview-list");

  if (!container || !listEl) return;

  if (!questions || questions.length === 0) {
    container.style.display = "none";
    return;
  }

  container.style.display = "flex";
  if (countBadge) countBadge.textContent = `✨ Đã phát hiện: ${questions.length} câu hỏi hợp lệ`;

  if (warnBadge) {
    if (warnings && warnings.length > 0) {
      warnBadge.style.display = "inline-block";
      warnBadge.textContent = `⚠️ ${warnings.length} lưu ý`;
      warnBadge.title = warnings.join("\n");
    } else {
      warnBadge.style.display = "none";
    }
  }

  const diffLabels = {
    easy: "Dễ",
    medium: "Trung bình",
    hard: "Khó",
    olympiad: "Nâng cao / Olympic"
  };

  const subjMap = {
    math: "Toán",
    vietnamese: "Tiếng Việt",
    english: "Tiếng Anh",
    science: "Khoa học & TNXH",
    informatics: "Tin học",
    history_geo: "Lịch sử & Địa lý"
  };

  listEl.innerHTML = questions.map((q, idx) => {
    const opts = q.options || [];
    const correctLetter = q.correct_answer || (opts.find(o => o.is_correct)?.id) || "A";
    const diffText = diffLabels[q.difficulty] || q.difficulty || "Trung bình";
    const subjText = subjMap[q.subject] || q.subject || "Toán";

    return `
      <div style="background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 14px; display: flex; flex-direction: column; gap: 8px;">
        <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 6px;">
          <div style="display: flex; align-items: center; gap: 8px; flex-wrap: wrap;">
            <span class="q-number-pill" style="font-size: 11.5px; padding: 2px 8px;">Câu ${idx + 1}</span>
            <span class="tag-badge" style="background: #eff6ff; color: #1d4ed8; font-size: 11px;">${subjText}</span>
            <span class="tag-grade" style="font-size: 11px;">Lớp ${q.grade || 5}</span>
            <span class="tag-badge" style="background: #fdf2f8; color: #be185d; font-size: 11px;">Độ khó: ${diffText}</span>
            ${q.has_handwriting ? `<span class="tag-badge" style="background: #fef3c7; color: #92400e; font-size: 11px; padding: 2px 7px; border: 1px solid #fde68a;" title="Câu hỏi có dấu vết chữ viết tay / chữ nháp học sinh">✍️ Chữ viết tay</span>` : ''}
            ${q.topic ? `<span class="tag-badge" style="background: #f1f5f9; color: #475569; font-size: 11px;">${q.topic}</span>` : ''}
          </div>
          <span style="font-weight: 700; color: #059669; font-size: 12px; background: #ecfdf5; padding: 2px 8px; border-radius: 4px;">
            Đáp án: [${correctLetter}]
          </span>
        </div>

        <div style="font-size: 13.5px; color: #1e293b; line-height: 1.5;">
          ${typeof formatMathSymbols === "function" ? formatMathSymbols(q.content_text || q.content_html || "") : (q.content_text || "")}
        </div>

        ${opts.length > 0 ? `
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 6px; font-size: 12.5px;">
            ${opts.map(o => {
              const isCorr = (o.id === correctLetter || o.is_correct);
              const bg = isCorr ? '#ecfdf5' : '#f8fafc';
              const border = isCorr ? '#a7f3d0' : '#e2e8f0';
              const color = isCorr ? '#065f46' : '#475569';
              const weight = isCorr ? '700' : 'normal';
              const contentText = typeof formatMathSymbols === "function" ? formatMathSymbols(o.content || "") : (o.content || "");
              return `
                <div style="padding: 6px 10px; border-radius: 6px; background: ${bg}; border: 1px solid ${border}; color: ${color}; font-weight: ${weight};">
                  <strong>${o.id}.</strong> ${contentText} ${isCorr ? '✓' : ''}
                </div>
              `;
            }).join('')}
          </div>
        ` : ''}

        ${q.explanation ? `
          <div style="font-size: 12px; color: #475569; background: #f8fafc; border-left: 3px solid #6366f1; padding: 6px 10px; border-radius: 4px;">
            <strong>💡 Lời giải:</strong> ${typeof formatMathSymbols === "function" ? formatMathSymbols(q.explanation) : q.explanation}
          </div>
        ` : ''}
      </div>
    `;
  }).join("");

  if (typeof renderMath === "function") {
    renderMath(listEl);
  }
}

async function confirmSaveAiQuestions() {
  if (!currentAiParsedQuestions || currentAiParsedQuestions.length === 0) {
    showToast("Không có câu hỏi nào để lưu", "warning");
    return;
  }

  const defaultSub = document.getElementById("ai-import-default-subject")?.value || "math";
  const questionsToSave = currentAiParsedQuestions.map(q => ({
    ...q,
    subject: q.subject || defaultSub,
    source_platform: q.source_platform || "ai_agent_import"
  }));

  try {
    const res = await fetch(`${API_BASE}/questions/bulk`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ questions: questionsToSave })
    });

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`);
    }

    const data = await res.json();
    const count = data.inserted_count || currentAiParsedQuestions.length;

    showToast(`🎉 Đã lưu thành công ${count} câu hỏi vào Ngân hàng CSDL!`, "success");
    loadDashboardStats();
    if (typeof State !== "undefined" && State.currentView === "bank") loadQuestions();
    if (typeof broadcastNewQuestions === "function") {
      broadcastNewQuestions(count, "AI Agent Import");
    }

    closeAiAgentImportModal();
  } catch (err) {
    showToast(`Lỗi khi lưu: ${err.message}`, "error");
  }
}
window.confirmSaveAiQuestions = confirmSaveAiQuestions;

function loadAiQuestionsToEditor() {
  if (!currentAiParsedQuestions || currentAiParsedQuestions.length === 0) {
    // If user clicked this directly without previewing first, execute preview first
    const rawText = document.getElementById("ai-import-raw-text")?.value?.trim() || "";
    if (rawText) {
      executeAiImport(false).then(() => {
        if (currentAiParsedQuestions && currentAiParsedQuestions.length > 0) {
          transferAiQuestionsToBatchStudio();
        }
      });
      return;
    } else {
      showToast("Vui lòng nhập hoặc kiểm tra dữ liệu trước", "warning");
      return;
    }
  }

  transferAiQuestionsToBatchStudio();
}
window.loadAiQuestionsToEditor = loadAiQuestionsToEditor;

function loadAiFileQuestionsToEditor() {
  if (!currentAiParsedQuestions || currentAiParsedQuestions.length === 0) {
    if (selectedAiFile) {
      executeAiFileImport(false).then(() => {
        if (currentAiParsedQuestions && currentAiParsedQuestions.length > 0) {
          transferAiQuestionsToBatchStudio();
        }
      });
      return;
    } else {
      showToast("Vui lòng chọn tệp trước", "warning");
      return;
    }
  }

  transferAiQuestionsToBatchStudio();
}
window.loadAiFileQuestionsToEditor = loadAiFileQuestionsToEditor;

function transferAiQuestionsToBatchStudio() {
  if (!currentAiParsedQuestions || currentAiParsedQuestions.length === 0) return;

  const defaultSub = document.getElementById("ai-import-default-subject")?.value || "math";
  closeAiAgentImportModal();

  // If startOcrBatchVerification exists, use it to start question review flow
  if (typeof startOcrBatchVerification === "function") {
    // Clone questions so modifications don't mutate preview cache
    const cloned = currentAiParsedQuestions.map(q => ({
      ...q,
      subject: q.subject || defaultSub,
      source_platform: q.source_platform || "ai_agent_import"
    }));
    startOcrBatchVerification(cloned, []);
    showToast(`✨ Đã nạp ${cloned.length} câu hỏi vào Trình Soạn thảo đối soát! Bạn có thể xem và sửa từng câu trước khi lưu.`, "success");
  } else {
    // Fallback: switch to manual view and load first question
    if (typeof switchView === "function") switchView("manual");
  }
}
